"""Self-evolution plugin: let the agent grow its own tools mid-conversation.

Enable in settings.json:
    {"plugins": {"enabled": ["evolve"],
                 "config": {"evolve": {"dir": ".codelet/evolved"}}}}

When the model hits a wall that a small, reusable capability would solve (a bespoke
parser, an API client, a data transform it keeps re-deriving in `bash`), it calls the
**`create_tool`** meta-tool. That writes a well-formed plugin file into the evolved
directory and hot-activates it into the *running* agent via `host.activate_plugin_file`,
so the new tool is callable on the very next turn -- no restart. On future startups the
plugin re-loads every file in that directory, so evolved tools persist.

Safety: this runs self-authored Python in-process, so the plugin is opt-in (built-in,
loads only when named in `plugins.enabled`). In ASK mode `create_tool` previews the
generated source through the normal diff-approval flow, so a human vets the code before
it is written and loaded. Each evolved file is a plain, readable plugin module you can
inspect, edit, or delete under the evolved directory.
"""
from __future__ import annotations

import keyword
import re
import textwrap
from pathlib import Path
from typing import Any

from ...plugins.base import PluginContext
from ...tools.base import Tool, ToolResult

DEFAULT_DIR = ".codelet/evolved"

# Names the agent must not clobber via create_tool -- the meta-tool itself and the
# core capabilities the loop depends on. (Overriding e.g. `bash` is a job for a
# deliberate plugin, not an in-conversation improvisation.)
PROTECTED_NAMES = {
    "create_tool", "bash", "read_file", "write_file", "edit_file",
    "glob", "grep", "task", "skill", "todo_write", "web_fetch",
}

_FILE_HEADER = '''"""Evolved tool `{name}`, authored by codelet's self-evolution.

{description}

Generated by the `evolve` plugin. Safe to read, edit, or delete -- it is a plain
plugin module: a `Tool` subclass plus a `PLUGIN` the loader picks up. Delete this
file to remove the tool; edit `_impl` to change its behaviour.
"""
from __future__ import annotations

from typing import Any

from codelet.tools.base import Tool, ToolResult
from codelet.plugins.base import PluginContext


def _impl(params: dict, tool: "Tool") -> Any:
    """Body authored by the agent. Reads `params` (validated against input_schema)
    and returns a string (tool output), a ToolResult, or None."""
'''

_FILE_BODY = '''

class {cls}(Tool):
    @property
    def name(self) -> str:
        return {name!r}

    @property
    def description(self) -> str:
        return {description!r}

    @property
    def input_schema(self) -> dict[str, Any]:
        return {schema!r}

    def execute(self, params: dict[str, Any]) -> ToolResult:
        try:
            result = _impl(params, self)
        except Exception as exc:  # a buggy evolved tool must not crash the agent
            return ToolResult(output=f"{name} raised: {{exc!r}}", is_error=True)
        if isinstance(result, ToolResult):
            return result
        return ToolResult(output="(no output)" if result is None else str(result))


class _Plugin:
    name = "evolved:{name}"

    def setup(self, ctx: PluginContext) -> None:
        ctx.register_tool({cls}())


PLUGIN = _Plugin()
'''

PROMPT_SECTION = (
    "## Self-evolution — you can build your own tools\n\n"
    "A **`create_tool`** meta-tool lets you add a new capability to yourself when no "
    "existing tool fits and the need is reusable or awkward to script inline. Prefer "
    "your built-in tools and `bash` for one-offs; reach for `create_tool` when you "
    "catch yourself re-deriving the same non-trivial logic, or when a clean, named "
    "capability would make the rest of the task tractable.\n\n"
    "How it works: you supply `name`, `description`, a JSON-schema `parameters` object, "
    "and a Python `code` body. The body runs with `params` (a dict matching your "
    "schema) in scope and should `return` a string (or a ToolResult). codelet writes "
    "it to a plugin file and activates it immediately — the new tool is callable on "
    "your next turn and persists for future sessions. Keep each tool small and "
    "single-purpose; put `import`s at the top of the body; validate inputs and return a "
    "clear error string on bad input. After creating a tool, call it to finish the task."
)


def _camel(name: str) -> str:
    return "".join(part.capitalize() for part in re.split(r"[^0-9A-Za-z]+", name) if part) + "Tool"


def _normalize_schema(parameters: Any) -> dict[str, Any]:
    """Accept either a full JSON-schema object or a bare properties map and return a
    well-formed object schema."""
    if not isinstance(parameters, dict) or not parameters:
        return {"type": "object", "properties": {}}
    if parameters.get("type") == "object" or "properties" in parameters:
        schema = dict(parameters)
        schema.setdefault("type", "object")
        schema.setdefault("properties", {})
        return schema
    # A bare {"query": {...}, "n": {...}} properties map.
    return {"type": "object", "properties": dict(parameters)}


def render_tool_source(name: str, description: str, schema: dict[str, Any], code: str) -> str:
    """Build a complete, importable plugin module for one evolved tool."""
    body = textwrap.indent(textwrap.dedent(code).strip() or "return None", "    ")
    header = _FILE_HEADER.format(name=name, description=description.strip())
    tail = _FILE_BODY.format(
        cls=_camel(name), name=name, description=description.strip(), schema=schema
    )
    return header + body + tail


class CreateToolTool(Tool):
    """The meta-tool. Bound to the live AgentLoop (`host`) so it can hot-activate
    what it writes."""

    def __init__(self, host: Any, evolved_dir: Path) -> None:
        self._host = host
        self._dir = evolved_dir

    @property
    def name(self) -> str:
        return "create_tool"

    @property
    def description(self) -> str:
        return (
            "Author a NEW tool for yourself and load it immediately (self-evolution). "
            "Use when no existing tool fits and the capability is reusable. Provide: "
            "`name` (snake_case identifier), `description` (when/how to use it), "
            "`parameters` (a JSON-schema object describing its inputs), and `code` "
            "(a Python function BODY that reads the `params` dict and returns a string "
            "or ToolResult; put imports at the top of the body). The tool is written to "
            "a plugin file, activated now, and available on your next turn. Then call it."
        )

    @property
    def input_schema(self) -> dict[str, Any]:
        return {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "snake_case identifier for the new tool, e.g. 'csv_stats'.",
                },
                "description": {
                    "type": "string",
                    "description": "What the tool does and when to use it (shown to you next turn).",
                },
                "parameters": {
                    "type": "object",
                    "description": "JSON-schema object for the tool's inputs "
                    "(e.g. {'type':'object','properties':{'path':{'type':'string'}},"
                    "'required':['path']}).",
                },
                "code": {
                    "type": "string",
                    "description": "Python function body. `params` (dict) is in scope; "
                    "`return` a string or ToolResult. Put imports at the top of the body.",
                },
                "overwrite": {
                    "type": "boolean",
                    "description": "Replace an existing evolved tool of the same name (default false).",
                },
            },
            "required": ["name", "description", "code"],
        }

    # ---- validation shared by preview + execute ----

    def _validate(self, params: dict[str, Any]) -> tuple[str, str, dict[str, Any], str, bool] | str:
        name = str(params.get("name") or "").strip()
        description = str(params.get("description") or "").strip()
        code = params.get("code") or ""
        overwrite = bool(params.get("overwrite", False))
        if not name or not code.strip():
            return "Error: 'name' and 'code' are required."
        if not name.isidentifier() or keyword.iskeyword(name):
            return f"Error: '{name}' is not a valid snake_case identifier."
        if name in PROTECTED_NAMES:
            return f"Error: '{name}' is a protected core tool and cannot be created/overridden."
        if not overwrite and (self._dir / f"{name}.py").exists():
            return f"Error: a tool named '{name}' already exists; pass overwrite=true to replace it."
        schema = _normalize_schema(params.get("parameters"))
        return name, description, schema, code, overwrite

    def preview_diff(self, params: dict[str, Any]) -> str | None:
        """ASK-mode approval shows the exact source that will be written + loaded."""
        parsed = self._validate(params)
        if isinstance(parsed, str):
            return None  # validation error path renders params instead; execute reports it
        name, description, schema, code, _ = parsed
        src = render_tool_source(name, description, schema, code)
        return f"# .codelet/evolved/{name}.py  (new self-authored tool)\n\n{src}"

    def execute(self, params: dict[str, Any]) -> ToolResult:
        parsed = self._validate(params)
        if isinstance(parsed, str):
            return ToolResult(output=parsed, is_error=True)
        name, description, schema, code, _ = parsed

        src = render_tool_source(name, description, schema, code)
        # Fail fast on syntax errors before touching disk or the live registry.
        try:
            compile(src, f"<evolved:{name}>", "exec")
        except SyntaxError as exc:
            return ToolResult(
                output=f"Generated tool did not compile: {exc}. Fix the `code` body and retry.",
                is_error=True,
            )

        self._dir.mkdir(parents=True, exist_ok=True)
        path = self._dir / f"{name}.py"
        path.write_text(src, encoding="utf-8")

        if self._host is None:  # no live loop (listing registry / tests): file only
            return ToolResult(output=f"Wrote {path} (no live session to activate into).")
        try:
            added = self._host.activate_plugin_file(path)
        except Exception as exc:
            return ToolResult(
                output=f"Wrote {path} but activation failed: {exc}. It will load on next start.",
                is_error=True,
            )
        added_str = ", ".join(added) or name
        return ToolResult(
            output=f"Created and activated tool '{added_str}'. It is now available — "
            f"call it to continue. Source saved at {path}."
        )


class EvolvePlugin:
    name = "evolve"

    def setup(self, ctx: PluginContext) -> None:
        evolved_dir = Path(str(ctx.config.get("dir") or DEFAULT_DIR))
        ctx.register_tool(CreateToolTool(ctx.host, evolved_dir))
        ctx.add_system_prompt_section(PROMPT_SECTION)
        ctx.register_command("evolve", lambda args: self._cmd(evolved_dir, args))
        # Re-load previously evolved tools so they persist across sessions.
        self._load_existing(ctx, evolved_dir)

    def _load_existing(self, ctx: PluginContext, evolved_dir: Path) -> None:
        if not evolved_dir.is_dir():
            return
        from ...plugins.loader import _load_from_file
        for f in sorted(evolved_dir.glob("*.py")):
            if f.name.startswith("_"):
                continue
            plugin = _load_from_file(f)
            if plugin is not None:
                try:
                    plugin.setup(ctx)  # registers its tool into the same registry
                except Exception as exc:  # a broken evolved file never breaks startup
                    import sys
                    print(f"[plugin] evolved tool {f.name} failed to load: {exc}", file=sys.stderr)

    def _cmd(self, evolved_dir: Path, args: str) -> str:
        if not evolved_dir.is_dir():
            return f"[evolve] no evolved tools yet (dir: {evolved_dir})"
        files = [f for f in sorted(evolved_dir.glob("*.py")) if not f.name.startswith("_")]
        if not files:
            return f"[evolve] no evolved tools yet (dir: {evolved_dir})"
        names = ", ".join(f.stem for f in files)
        return f"[evolve] {len(files)} evolved tool(s) in {evolved_dir}: {names}"


PLUGIN = EvolvePlugin()
